- name: deploy ubuntu
  hosts: ubuntu-test
  gather_facts: true
  vars_prompt:
    - name: prompt_user
      prompt: Enter username
      private: no
    - name: prompt_pass
      prompt: Enter password
    - name: prompt_domain_user
      prompt: Enter domain username
      private: no
    - name: prompt_domain_pass
      prompt: "Enter password for domain user"
  vars:
    ansible_become: True
    ansible_become_method: sudo
    ansible_user: "{{ prompt_user }}"
    ansible_password: "{{ prompt_pass }}"
    ansible_become_password: "{{ prompt_pass }}"
    domain_user: "{{prompt_domain_user}}"
    domain_pass: "{{prompt_domain_pass}}"
    domain: office.sspk.spb.ru
    is_sec_dns: true 
#    proxy_address: "http://192.168.1.1:3128/"
  roles:
#    - role: ubuntu_disable_ipv6
    - role: ubuntu_set_local_rep
    - role: ubuntu_default_deploy
      vars:
        ntp_servers: "ntp.office.sspk.spb.ru ru.pool.ntp.org"
    - role: ubuntu_join_domain
      vars:
        admins_group: "Linux Admin"
#        dedicated_user: "{{domain_user}}"
    - role: ubuntu_zabbix-agent2
      vars:
        zabbix_server: "rover-zbx-proxy.office.sspk.spb.ru"
        zabbix_version: 5.0
    - role: ubuntu_distribute_ca
      vars:
        rootca_path: "http://pki.office.sspk.spb.ru/sspk-root-ca/sspk-root-ca.crt"
#    - role: ubuntu_docker
#      vars:
#        docker_compose_version: 1.29.2
