- name: install packages for realm
  ansible.builtin.apt:
    pkg:
    - realmd
    - oddjob
    - oddjob-mkhomedir
    - sssd
    - sssd-tools
    - adcli
    - samba
    - krb5-user

- name: check domain
  shell:
    cmd: realm list {{domain}} | wc -l
  register: domain_check_result

- name: join domain
  ansible.builtin.expect:
    command: realm join --user={{domain_user}}@{{domain|upper}} {{domain|upper}} --install=/
    responses:
      (?i)password: "{{domain_pass}}"
  when: domain_check_result.stdout == "0"

- name: modify /etc/sssd/sssd.conf (use user's short name)
  ansible.builtin.replace:
    path: /etc/sssd/sssd.conf
    regexp: 'use_fully_qualified_names = True'
    replace: 'use_fully_qualified_names = False'

- name: modify /etc/sssd/sssd.conf (params for perfomance)
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    line: '{{ item }}'
    insertafter: EOF
  with_items:
    - 'ignore_group_members = True'
    - 'ldap_group_nesting_level = 0'

- name: modify /etc/sssd/sssd.conf (add ssh service)
  ansible.builtin.replace:
    path: /etc/sssd/sssd.conf
    regexp: 'services =.*$'
    replace: 'services = nss, pam, ssh'

- name: modify /etc/sssd/sssd.conf (add params for ssh service)
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    line: '{{ item }}'
    insertafter: EOF
  with_items:
    - 'ldap_user_extra_attrs = altSecurityIdentities:altSecurityIdentities'
    - 'ldap_user_ssh_public_key = altSecurityIdentities'
    - 'ldap_use_tokengroups = True'

- name: modify /etc/ssh/sshd_config (get ssh pub key from ad)
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '#AuthorizedKeysCommand .*$'
    replace: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'

- name: modify /etc/ssh/sshd_config (get ssh pub key from ad)
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '#AuthorizedKeysCommandUser .*$'
    replace: 'AuthorizedKeysCommandUser nobody'

- name: modify /etc/pam.d/common-session (create home folders for domain users)
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    insertafter: 'pam_unix.so'
    line: 'session required pam_mkhomedir.so skel=/etc/skel/ umask=0022'  

- name: pause for join domain (3 min)
  pause:
    minutes: 3
  when: domain_check_result.stdout == "0"

- name: add permit to admins group
  shell: realm permit -g "{{admins_group}}@{{domain}}"
  when: admins_group is defined

- name: add admins group to /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: EOF
    line: '%{{ admins_group | lower | replace(" ","\ ")}} ALL=(ALL) ALL'
    validate: /usr/sbin/visudo -cf %s
  when: admins_group is defined

- name: add permit for dedicated user
  shell: realm permit "{{dedicated_user}}@{{domain}}"
  when: dedicated_user is defined

- name: add dedicated user to /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: EOF
    line: '{{dedicated_user}} ALL=(ALL) ALL'
    validate: /usr/sbin/visudo -cf %s
  when: dedicated_user is defined

- name: restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: create nsupdate.conf
  ansible.builtin.template:
    src: nsupdate.conf.j2
    dest: /etc/nsupdate.conf

- name: add dns update job to cron (for sec dns update)
  ansible.builtin.cron:
    name: update dns
    minute: "*/10"
    user: root
    job: "klist -c /tmp/krb_cache_dns >> /dev/null || ( HOSTNAME_UP=`bash -c 'echo $HOSTNAME' | tr '[a-z]' '[A-Z]'`; kinit -k -t /etc/krb5.keytab -c /tmp/krb_cache_dns $HOSTNAME_UP$ >> /dev/null ) && (env KRB5CCNAME=/tmp/krb_cache_dns nsupdate -g /etc/nsupdate.conf)"
  when: is_sec_dns is defined and is_sec_dns

- name: add dns update job to cron (for unsec dns update)
  ansible.builtin.cron:
    name: update dns
    minute: "*/10"
    user: root
    job: "nsupdate -g /etc/nsupdate.conf"
  when: is_sec_dns is not defined or not is_sec_dns
