- name: install zabbix sources list from deb
  ansible.builtin.apt: 
    deb: "{{zabbix_repo_deb_path}}"
  environment:
    http_proxy: "{{proxy_address | default('')}}"
    https_proxy: "{{proxy_address | default('')}}"
  when: zabbix_repo_deb_path is defined

- name: push zabbix sources list from template
  ansible.builtin.template:
    src: "{{ansible_distribution|lower}}_zabbix.list.j2"
    dest: "/etc/apt/sources.list.d/zabbix.list"
  when: zabbix_repo_deb_path is not defined

- name: install zabbix-agent2
  ansible.builtin.apt:
    name: zabbix-agent2
    update_cache: yes

- name: push zabbix_agent2.conf
  ansible.builtin.template:
    src: "zabbix_agent2.conf.j2"
    dest: "/etc/zabbix/zabbix_agent2.conf"
  notify: restart zabbix-agent2

- name: add custom parameters for zabbix
  ansible.builtin.template:
    src: "{{item}}.conf.j2"
    dest: "/etc/zabbix/zabbix_agent2.d/{{item}}.conf"
  loop:
    - "reboot_required"
    - "apt_updates"
    - "systemd"
    - "net"
  notify: restart zabbix-agent2

- name: enable zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes
